version: 0.0
os: linux
files:
  - source: backend/
    destination: home/ubuntu/awsapp
hooks:
  Install:
    - location: backend/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: backend/start_server.sh
      timeout: 300
      runas: root
