version: 0.0
os: linux
files:
  - source: backend.zip
    destination: /awsapp
hooks:
  BeforeInstall:
    - script: |
        echo "Unzipping backend.zip..."
        unzip /awsapp/backend.zip -d /awsapp
        echo "Unzip complete. Cleaning up..."
        rm /awsapp/backend.zip
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
